### ISSUE TITLE
GRAD_SpectatorSpawnLogic doesn't initialize mission

### ISSUE THREAD

**Issue by tanaaKa** [gruppe-adler/GRAD-Spectator#2]
Using `GRAD_SpectatorSpawnLogic` class as the spawn logic in `SCR_RespawnLogicSystemComponent` prevents the world file from initializing in `SCR_BaseGameMode`.

I'm not sure if this has been broken since 1.0 release as I've used it successfully prior to 1.0 release, but currently, using the spectator spawn logic doesn't allow the mission to initialize. The error.log shows nothing specific but I can provide one if needed.

I've narrowed it down to the spawn logic as changing it to menu spawn logic or auto spawn logic allows the mission to initialize.

**Comment by y0014984** [comment]
I will have a look into it. Thank you for your Feedback.

**Comment by y0014984** [comment]
@tanaaKa I think I could fix it. Please checkout the newly published version 0.1.5 in the Arma Reforger Workshop. BI changed some things so my custom SpectatorSpawnLogic does not work anymore. So I modded the Vanilla MenuSpawnLogic. The procedure stays the same except that you do not need to change the spawn logic (it stays the Vanilla MenuSpawnLogic) but you still need to fill the required settings for the expected bahavior. Please give me a feedback if this is now working for you.

**Comment by y0014984** [comment]
No feedback is good feedback. I close this issue for now.
